name: deploy_frontend
#Deploys when push is made from frontend folder

on:
    push:
        branches: [ main ]
        paths:
            - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.Azure_Credentials }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureresumelearnacg --auth-mode key --overwrite -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumelearn" --name "azureresumelearn" --resource-group "azure-resume-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
